import { AccountStatus, Account, ContentItem, AffiliateLink, Proxy, ContentStatus } from './types';

export const INITIAL_ACCOUNTS: Account[] = [
  // ==========================================
  // --- SETUP 0: Shortlink (API NODES) ---
  // ==========================================
  { id: 'sl1', setup: 'Shortlink', platform: 'oii.io', profileName: 'bdtoolx', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '4ae5b4d1b0b87fa8b45e42f225e26bf3b028e8a9', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'API Token Active' },
  { id: 'sl2', setup: 'Shortlink', platform: 'fc.lc', profileName: 'bdtoolx', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: 'f160fc9b8ac819529efb9c612a3c0ffb6ef648d5', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Full Page Script Ready' },
  { id: 'sl3', setup: 'Shortlink', platform: 'shrinkme.io', profileName: 'RAJIB KUMAR SAHA', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: 'bc4d877bc1556fcfac362f362dfd2d8fb451c313', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Mass Shrinker Active' },
  { id: 'sl4', setup: 'Shortlink', platform: 'shrinkearn.com', profileName: 'RAJIB KUMAR SAHA', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '43d9f6869978cc6e848417b421587d4d7c3b8dbd', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Earnings Node' },
  { id: 'sl5', setup: 'Shortlink', platform: 'gplinks.com', profileName: 'RAJIB KUMAR SAHA', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '44f0abb70dcad7225128110dc8cf998018a32442', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'High CPM Node' },
  { id: 'sl6', setup: 'Shortlink', platform: 'cuty.io', profileName: 'bdtoolx', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '603836642af86bf2a9bbfd1d8', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Quick API Active' },
  { id: 'sl7', setup: 'Shortlink', platform: 'upfiles.com', profileName: 'bdtoolx', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '643a0b5d1145e218ce161e86fe643bb0', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'File Upload API' },
  { id: 'sl8', setup: 'Shortlink', platform: 'uploady.io', profileName: 'bdtoolx', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '1saep52buejc4ngwo', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Monetized Hosting' },
  { id: 'sl9', setup: 'Shortlink', platform: 'exe.io', profileName: 'bdtoolx', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '3da97b7b7c586762c21ccae186cb038355af4174', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Global Shortener' },
  { id: 'sl10', setup: 'Shortlink', platform: 'clicksfly.com', profileName: 'RAJIB KUMAR SAHA', userId: 'Rajibrj03', email: 'rajibsaha.rj2@gmail.com', password: 'BD@2026@toolX', apiKey: '38b458e0cec6c68fbddb370fe547a688cb37e0f2', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Premium Rates' },
  { id: 'sl11', setup: 'Shortlink', platform: 'ouo.io', profileName: 'bdtoolx', userId: '3SvRMAWc', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '3SvRMAWc', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Token: 3SvRMAWc' },
  { id: 'sl12', setup: 'Shortlink', platform: 'bc.vc', profileName: 'RAJIB KUMAR SAHA', userId: '479536', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '0b4b685f6922fd18cc05ea9120808cde', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'UID: 479536' },
  { id: 'sl13', setup: 'Shortlink', platform: 'adfoc.us', profileName: 'RAJIB KUMAR SAHA', userId: '874960', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: 'dde3a65de9076fe5826e516e88fafa98', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'UID: 874960' },
  { id: 'sl14', setup: 'Shortlink', platform: 'adfly.cc', profileName: 'RAJIB KUMAR SAHA', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: '7261ee51cad93cfe0d77da8726779f06d8106492', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Legacy Adfly' },
  { id: 'sl15', setup: 'Shortlink', platform: 'clk.sh', profileName: 'bdtoolx', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: 'e85d3c63270ec0b2faab1e9d7dc6bdc324739661', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'High Traffic' },
  { id: 'sl16', setup: 'Shortlink', platform: 'adfly.site', profileName: 'bdtoolx', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@toolX', apiKey: 'e9e72a5ba43fc966f7054a474a23d47fffeff389', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Alternative Site' },

  // ==========================================
  // --- SETUP 1: BD ToolX (SYNCED) ---
  // ==========================================
  { id: 'btx1', setup: 'BD ToolX', platform: 'Instagram', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io (Bio Link)' },
  { id: 'btx2', setup: 'BD ToolX', platform: 'YouTube', profileName: 'BD ToolX', userId: '@bdtoolx', email: 'm94992189@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Ouo.io (US Tech Videos)' },
  { id: 'btx3', setup: 'BD ToolX', platform: 'X (Twitter)', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC (Viral Tweets)' },
  { id: 'btx4', setup: 'BD ToolX', platform: 'Pinterest', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'GPLinks.com (Product Pins)' },
  { id: 'btx5', setup: 'BD ToolX', platform: 'Blogger', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'BC.VC (Auto-Link Script)' },
  { id: 'btx6', setup: 'BD ToolX', platform: 'Reddit', profileName: 'BD ToolX', userId: 'bdtoolxmedia', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Exe.io (US Communities)' },
  { id: 'btx7', setup: 'BD ToolX', platform: 'Mastodon', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkEarn.com' },
  { id: 'btx8', setup: 'BD ToolX', platform: 'Medium', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ClicksFly.com' },
  { id: 'btx9', setup: 'BD ToolX', platform: 'Tumblr', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.cc' },
  { id: 'btx10', setup: 'BD ToolX', platform: 'Bluesky', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Oii.io.com' },
  { id: 'btx11', setup: 'BD ToolX', platform: 'Vimeo', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.site' },
  { id: 'btx12', setup: 'BD ToolX', platform: 'FB Profile', profileName: 'Soniya Sultana', userId: 'soniya02sul', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC (Main Post)' },
  { id: 'btx13', setup: 'BD ToolX', platform: 'FB Profile (S)', profileName: 'Puja Saha', userId: 'puja.saha.58984', email: 'bdtoolx@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Cuty.io (Switch)' },
  { id: 'btx14', setup: 'BD ToolX', platform: 'FB Page', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'GPLinks.com' },
  { id: 'btx15', setup: 'BD ToolX', platform: 'FB Group 1', profileName: 'BD ToolX', userId: 'bdtoolx', email: 'bdtoolx@gmail.com', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io' },
  { id: 'btx16', setup: 'BD ToolX', platform: 'FB Group 2', profileName: 'Lesbian Lounge', userId: 'lesbianloungebd', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Uploady.io (Special Content)' },
  { id: 'btx17', setup: 'BD ToolX', platform: 'Telegram (M)', profileName: 'BD Tools', userId: 'bdtoolsus', email: '+880160867312', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC Bot API' },
  { id: 'btx18', setup: 'BD ToolX', platform: 'TG Channel 1', profileName: 'BD ToolX', userId: 'bdtoolxmedia', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Mass Shrinker (All)' },
  { id: 'btx19', setup: 'BD ToolX', platform: 'WA Channel', profileName: 'BD ToolX', userId: '[Link]', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Quick Link (Ouo.io)' },
  { id: 'btx20', setup: 'BD ToolX', platform: 'WA Group', profileName: 'BD ToolX', userId: '[Link]', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Quick Link (ShrinkMe.io)' },
  { id: 'btx21', setup: 'BD ToolX', platform: 'WhatsApp (M)', profileName: 'Rajib', userId: '+880173161027', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Bookmarklet (Ouo.io)' },

  // ==========================================
  // --- SETUP 2: SwiftCash Link (SYNCED) ---
  // ==========================================
  { id: 'sc1', setup: 'SwiftCash Link', platform: 'Instagram', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkEarn.com' },
  { id: 'sc2', setup: 'SwiftCash Link', platform: 'Facebook (Prof)', profileName: 'Abhimani Puja', userId: 'ItsPujaAbhimani', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Exe.io' },
  { id: 'sc3', setup: 'SwiftCash Link', platform: 'Facebook (Pag)', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'GPLinks.com' },
  { id: 'sc4', setup: 'SwiftCash Link', platform: 'Facebook (Gro)', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ClicksFly.com' },
  { id: 'sc5', setup: 'SwiftCash Link', platform: 'Facebook (Swit)', profileName: 'ক্ষুধার্থ বালক', userId: 'KshudarthaX', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Cuty.io' },
  { id: 'sc6', setup: 'SwiftCash Link', platform: 'TikTok', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC (Viral Shorts)' },
  { id: 'sc7', setup: 'SwiftCash Link', platform: 'YouTube', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Ouo.io' },
  { id: 'sc8', setup: 'SwiftCash Link', platform: 'X (Twitter)', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io' },
  { id: 'sc9', setup: 'SwiftCash Link', platform: 'Pinterest', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'BC.VC' },
  { id: 'sc10', setup: 'SwiftCash Link', platform: 'Telegram (Mair)', profileName: 'SwiftCash', userId: 'SwiftCash20', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC Bot API' },
  { id: 'sc11', setup: 'SwiftCash Link', platform: 'Telegram (Ch 1)', profileName: 'SwiftCash Link', userId: '@swiftcashlink', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Mass Shrinker' },
  { id: 'sc12', setup: 'SwiftCash Link', platform: 'Telegram (Ch 2)', profileName: 'Digital Tools Zor', userId: '@digitaltoolszor', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Quick Link' },
  { id: 'sc13', setup: 'SwiftCash Link', platform: 'WhatsApp (Ch)', profileName: 'SwiftCash Link', userId: 'N/A', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Ouo.io' },
  { id: 'sc14', setup: 'SwiftCash Link', platform: 'WhatsApp (Grp)', profileName: 'SwiftCash Link', userId: 'N/A', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io' },
  { id: 'sc15', setup: 'SwiftCash Link', platform: 'WhatsApp (Num)', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Bookmarklet' },
  { id: 'sc16', setup: 'SwiftCash Link', platform: 'Blogger', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Full Page Script (GPLinks)' },
  { id: 'sc17', setup: 'SwiftCash Link', platform: 'Reddit', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Exe.io' },
  { id: 'sc18', setup: 'SwiftCash Link', platform: 'Mastodon', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkEarn.com' },
  { id: 'sc19', setup: 'SwiftCash Link', platform: 'Medium', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ClicksFly.com' },
  { id: 'sc20', setup: 'SwiftCash Link', platform: 'Tumblr', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.cc' },
  { id: 'sc21', setup: 'SwiftCash Link', platform: 'Bluesky', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Oii.io.com' },
  { id: 'sc22', setup: 'SwiftCash Link', platform: 'Vimeo', profileName: 'SwiftCash Link', userId: 'swiftcashlink', email: 'swiftcashlink@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.site' },

  // ==========================================
  // --- SETUP 3: AffiRise Network (SYNCED) ---
  // ==========================================
  { id: 'af1', setup: 'AffiRise Network', platform: 'Instagram', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'BC.VC' },
  { id: 'af2', setup: 'AffiRise Network', platform: 'TikTok', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC' },
  { id: 'af3', setup: 'AffiRise Network', platform: 'YouTube', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Ouo.io' },
  { id: 'af4', setup: 'AffiRise Network', platform: 'X (Twitter)', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io' },
  { id: 'af5', setup: 'AffiRise Network', platform: 'Pinterest', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'GPLinks.com' },
  { id: 'af6', setup: 'AffiRise Network', platform: 'Blogger', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Full Page Script (BC.VC)' },
  { id: 'af7', setup: 'AffiRise Network', platform: 'Reddit', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Exe.io' },
  { id: 'af8', setup: 'AffiRise Network', platform: 'Mastodon', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkEarn.com' },
  { id: 'af9', setup: 'AffiRise Network', platform: 'Medium', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ClicksFly.com' },
  { id: 'af10', setup: 'AffiRise Network', platform: 'Tumblr', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.cc' },
  { id: 'af11', setup: 'AffiRise Network', platform: 'Bluesky', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Oii.io.com' },
  { id: 'af12', setup: 'AffiRise Network', platform: 'Vimeo', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.site' },
  { id: 'af13', setup: 'AffiRise Network', platform: 'FB Profile', profileName: 'Vorer Shishir Kona', userId: 'ShishirKonausa', email: 'affirisenetwork@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC' },
  { id: 'af14', setup: 'AffiRise Network', platform: 'FB Page', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'GPLinks.com' },
  { id: 'af15', setup: 'AffiRise Network', platform: 'FB Group', profileName: 'AffiRise Network', userId: 'affirisenetwork', email: 'affirisenetwork@gmail.com', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ClicksFly.com' },
  { id: 'af16', setup: 'AffiRise Network', platform: 'Telegram (M)', profileName: 'AffiRise', userId: '@affirise', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC Bot API' },
  { id: 'af17', setup: 'AffiRise Network', platform: 'TG Channel 1', profileName: 'Smart Deals Hut', userId: '@smartdealshul', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Mass Shrinker' },
  { id: 'af18', setup: 'AffiRise Network', platform: 'TG Channel 2', profileName: 'AffiRise Network', userId: '@affirisenetwork', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Quick Link' },
  { id: 'af19', setup: 'AffiRise Network', platform: 'WA Channel', profileName: 'AffiRise Network', userId: 'N/A', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Ouo.io' },
  { id: 'af20', setup: 'AffiRise Network', platform: 'WA Group', profileName: 'AffiRise Network', userId: 'N/A', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io' },
  { id: 'af21', setup: 'AffiRise Network', platform: 'WhatsApp (M)', profileName: 'Smart Deals Hut', userId: '1789935246', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Bookmarklet' },

  // ==========================================
  // --- SETUP 4: LinkSurge Pro (SYNCED) ---
  // ==========================================
  { id: 'lp1', setup: 'LinkSurge Pro', platform: 'FB Profile', profileName: 'Rj Rajib', userId: 'rj.rajib03', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Uploady.io (Critical Traffic)' },
  { id: 'lp2', setup: 'LinkSurge Pro', platform: 'FB Page', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Upfiles.com (Critical)' },
  { id: 'lp3', setup: 'LinkSurge Pro', platform: 'FB Group', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Cuty.io' },
  { id: 'lp4', setup: 'LinkSurge Pro', platform: 'FB Switch 1', profileName: 'Taspia Islam Mim', userId: 'UnknownStar0.2', email: 'N/A', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Cuty.io' },
  { id: 'lp5', setup: 'LinkSurge Pro', platform: 'FB Switch 2', profileName: 'ভোরের সূর্য', userId: 'ভোরের সূর্য', email: 'N/A', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Cuty.io' },
  { id: 'lp6', setup: 'LinkSurge Pro', platform: 'Instagram', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io' },
  { id: 'lp7', setup: 'LinkSurge Pro', platform: 'TikTok', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC' },
  { id: 'lp8', setup: 'LinkSurge Pro', platform: 'YouTube', profileName: 'LinkSurge Pro', userId: '@linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Ouo.io' },
  { id: 'lp9', setup: 'LinkSurge Pro', platform: 'X (Twitter)', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Exe.io' },
  { id: 'lp10', setup: 'LinkSurge Pro', platform: 'Pinterest', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'GPLinks.com' },
  { id: 'lp11', setup: 'LinkSurge Pro', platform: 'Blogger', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'BC.VC' },
  { id: 'lp12', setup: 'LinkSurge Pro', platform: 'Reddit', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkEarn.com' },
  { id: 'lp13', setup: 'LinkSurge Pro', platform: 'Mastodon', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ClicksFly.com' },
  { id: 'lp14', setup: 'LinkSurge Pro', platform: 'Medium', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.cc' },
  { id: 'lp15', setup: 'LinkSurge Pro', platform: 'Tumblr', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Oii.io.com' },
  { id: 'lp16', setup: 'LinkSurge Pro', platform: 'Bluesky', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.site' },
  { id: 'lp17', setup: 'LinkSurge Pro', platform: 'Vimeo', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'linksurgepro@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Clk.sh' },
  { id: 'lp18', setup: 'LinkSurge Pro', platform: 'Telegram (M)', profileName: 'LinkSurge', userId: 'linksurge', email: 'N/A', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC Bot API' },
  { id: 'lp19', setup: 'LinkSurge Pro', platform: 'TG Channel 1', profileName: 'LinkSurge Pro', userId: 'linksurgepro', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Mass Shrinker' },
  { id: 'lp20', setup: 'LinkSurge Pro', platform: 'TG Channel 2', profileName: 'Online Offers Lab', userId: 'onlineofferslab', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Quick Link' },
  { id: 'lp21', setup: 'LinkSurge Pro', platform: 'WA Channel', profileName: 'LinkSurge Pro', userId: 'N/A', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Ouo.io' },
  { id: 'lp22', setup: 'LinkSurge Pro', platform: 'WA Group', profileName: 'LinkSurge Pro', userId: 'N/A', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io' },
  { id: 'lp23', setup: 'LinkSurge Pro', platform: 'WhatsApp (M)', profileName: 'LinkSurge', userId: 'N/A', email: '8801733268800', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Bookmarklet' },

  // ==========================================
  // --- SETUP 5: ZipLink Flow (SYNCED) ---
  // ==========================================
  { id: 'zf1', setup: 'ZipLink Flow', platform: 'Instagram', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'BC.VC' },
  { id: 'zf2', setup: 'ZipLink Flow', platform: 'TikTok', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC' },
  { id: 'zf3', setup: 'ZipLink Flow', platform: 'YouTube', profileName: 'ZipLink Flow', userId: '@ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Ouo.io' },
  { id: 'zf4', setup: 'ZipLink Flow', platform: 'X (Twitter)', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkMe.io' },
  { id: 'zf5', setup: 'ZipLink Flow', platform: 'Pinterest', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'GPLinks.com' },
  { id: 'zf6', setup: 'ZipLink Flow', platform: 'Blogger', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Full Page Script' },
  { id: 'zf7', setup: 'ZipLink Flow', platform: 'Reddit', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Exe.io' },
  { id: 'zf8', setup: 'ZipLink Flow', platform: 'Mastodon', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ShrinkEarn.com' },
  { id: 'zf9', setup: 'ZipLink Flow', platform: 'Medium', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'ClicksFly.com' },
  { id: 'zf10', setup: 'ZipLink Flow', platform: 'Tumblr', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.cc' },
  { id: 'zf11', setup: 'ZipLink Flow', platform: 'Bluesky', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Oii.io.com' },
  { id: 'zf12', setup: 'ZipLink Flow', platform: 'Vimeo', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'AdFly.site' },
  { id: 'zf13', setup: 'ZipLink Flow', platform: 'FB Profile', profileName: 'Tanisha Rahama', userId: 'ziplink', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Uploady.io (Critical)' },
  { id: 'zf14', setup: 'ZipLink Flow', platform: 'FB Page', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'ziplinkflow@gmail.com', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Upfiles.com (Critical)' },
  { id: 'zf15', setup: 'ZipLink Flow', platform: 'FB Group', profileName: 'ZipLink Flow', userId: 'ziplinkflow', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Cuty.io' },
  { id: 'zf16', setup: 'ZipLink Flow', platform: 'Telegram (M)', profileName: 'ZipLink', userId: 'ZipLinkus', email: 'ziplinkflow@gmail.com', password: 'BD@2026@tool', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'FC.LC Bot API' },
  { id: 'zf17', setup: 'ZipLink Flow', platform: 'TG Channel 1', profileName: 'ZipLink Flow', userId: '@ziplinkflow', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Mass Shrinker' },
  { id: 'zf18', setup: 'ZipLink Flow', platform: 'WA Channel', profileName: 'ZipLink Flow', userId: 'N/A', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Quick Link' },
  { id: 'zf19', setup: 'ZipLink Flow', platform: 'WA Group', profileName: 'ZipLink Flow', userId: 'N/A', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Quick Link' },
  { id: 'zf20', setup: 'ZipLink Flow', platform: 'WhatsApp (M)', profileName: 'ZipLink', userId: '1511884322', email: 'N/A', password: 'N/A', status: AccountStatus.ACTIVE, createdAt: 'N/A', lastPostAt: 'N/A', score: 100, notes: 'Bookmarklet' }
];

export const INITIAL_CONTENT: ContentItem[] = [
  { id: '1', text: 'New promo for BD ToolX users!', platform: 'Facebook', scheduledTime: '2026-02-01 10:00', status: ContentStatus.SCHEDULED },
];

export const INITIAL_AFFILIATES: AffiliateLink[] = [
  { id: '1', network: 'Amazon', product: 'Marketing Gear', link: 'https://amzn.to/example', clicks: 500, revenue: 120.00 },
];

export const INITIAL_PROXIES: Proxy[] = [
  { id: '1', ipPort: '10.0.0.1:8080', status: 'ONLINE' },
];